### ISSUE TITLE
Attempted to remove the room which is not in the room list.

### ISSUE THREAD

**Issue by nikhilGitrepo** [himajakethiri/MSCS721-roomScheduler#1]
When i tried to remove the room which is not in the room list, program is terminating and displaying the main menu again with out any proper error or display message.

Defect found in "To remove the rooms" ,  Line No: 102

Steps required:
1. check if the room is available or not
2. if not, try to display an error message.

**Comment by himajakethiri** [comment]
This issue is fixed by adding else condition to removeRoom()
and by checking room exist using if condition to findRoomIndex() method.
Line number:146,147,149,150 added.
