### ISSUE TITLE
Attempted to import the rooms and room schedules to json

### ISSUE THREAD

**Issue by gopipara** [himajakethiri/MSCS721-roomScheduler#3]
tried to import the rooms and room schedules to json, which is not working properly.

Defect found in "Importing the meeting details from JSON files".
Line number: 267

Suggestion: Import method is written correctly but u have to call the import function in the case statements which are defined in the main method.

**Comment by himajakethiri** [comment]
This issue was fixed by adding case statements in the code.
Line number:63 to 73 added.
