### ISSUE TITLE
Attempted to schedule the room which is not in the room list

### ISSUE THREAD

**Issue by gopipara** [himajakethiri/MSCS721-roomScheduler#4]
I have tried to schedule the room which is not in the room list. the program should not schedule the meeting for the room which is not available.

Defect found in "Schedule the room if it is available"
Line number: 124

Suggestion: use the condition that checks the room if it is available in the room list or not before adding schedule to it. 
-->you can use the following syntax to find the room index and the room.

if(findRoomIndex(roomList,name) ==0

**Comment by himajakethiri** [comment]
This issue was fixed by adding if (findRoomIndex(roomList, name) != -1).
Line number:178,206,207,208 added.
