### ISSUE TITLE
Attempted to add meeting to the room which is not empty

### ISSUE THREAD

**Issue by gopipara** [himajakethiri/MSCS721-roomScheduler#5]
Problem: Not checking whether the available room is empty or not before adding meetings to the room.

Defect found in " Schedule the room if it is available"
Line number: '124'

Suggestion: 
Use the condition " if(roomList.isEmpty()) " to check whether the available room is empty or not.

**Comment by himajakethiri** [comment]
This issue was fixed by adding if (roomList.size() > 0) to check the room size.
Line number:175,209,210,211 added.
